// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Drivetrain.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/MecanumDrive.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Drivetrain::Drivetrain() : Subsystem("Drivetrain") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    frontLeft = RobotMap::drivetrainfrontLeft;
    frontRight = RobotMap::drivetrainfrontRight;
    rearLeft = RobotMap::drivetrainrearLeft;
    rearRight = RobotMap::drivetrainrearRight;
    robotDrive = RobotMap::drivetrainRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    gyro = RobotMap::drivetrainGyro;
}

void Drivetrain::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new MecanumDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Drivetrain::DriveStraight() {
	robotDrive->MecanumDrive_Cartesian(0.0, 1.0, 0.0, gyro->GetAngle());
}

void Drivetrain::MechanumDrive(std::shared_ptr<Joystick> joystick) {
	robotDrive->MecanumDrive_Cartesian(joystick->GetRawAxis(0), joystick->GetRawAxis(1), joystick->GetRawAxis(4), gyro->GetAngle());
}

void Drivetrain::Stop() {
	robotDrive->StopMotor();
}

void Drivetrain::Turn() {

}

void Drivetrain::TurnGyro() {

}
// Put methods for controlling this subsystem
// here. Call these from Commands.

