// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "VisionHandler.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

VisionHandler::VisionHandler() : Subsystem("VisionHandler") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	visionTable = NetworkTable::GetTable("vision");
	missedCount = 0;
	visionTuple = RobotMap::visionTuple;
}

void VisionHandler::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


std::shared_ptr<VisionHandler::VisionTuple> VisionHandler::getCurrentTuple() {
	return visionTuple;
}

void VisionHandler::updateSubsystem() {
	static std::shared_ptr<VisionHandler::VisionTuple> newTuple;
	newTuple.reset(new VisionHandler::VisionTuple(-999, -999, -999));
	newTuple->setAngle(visionTable->GetNumber("gearAngle", -999));
	newTuple->setDistance(visionTable->GetNumber("gearDistance", -999));
	newTuple->setCenter(visionTable->GetNumber("gearCV",-999));
	if(newTuple->isDefault()) {
		missedCount++;
	} else {
		this->visionTuple = newTuple;
	}
	if(missedCount > CACHE_MISSED_NUM) {
		missedCount = 0;
		this->visionTuple = newTuple;
	}
}
