// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Ascend.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Ascend::Ascend(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::climber.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Ascend::Initialize() {
	//j = Robot::oi->getJoystick1();
	if (Robot::allianceColor == DriverStation::Alliance::kBlue){
		Robot::arduinoComm->WriteTest("B"); // Will use color blue for animations on LEDS.
	} else if (Robot::allianceColor == DriverStation::Alliance::kRed) {
		Robot::arduinoComm->WriteTest("R"); // Will use red color.
	} else if (Robot::allianceColor == DriverStation::Alliance::kInvalid) {
		Robot::arduinoComm->WriteTest("Y"); // Will use red color.
	}
	Robot::arduinoComm->WriteTest("b");
}

// Called repeatedly when this Command is scheduled to run
void Ascend::Execute() {
		Robot::climber->Set(1.0);
}

// Make this return true when this Command no longer needs to run execute()
bool Ascend::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Ascend::End() {
	Robot::climber->Stop();
	Robot::arduinoComm->WriteTest("w");
	if (Robot::allianceColor == DriverStation::Alliance::kBlue){
		Robot::arduinoComm->WriteTest("B"); // Will use color blue for animations on LEDS.
	} else if (Robot::allianceColor == DriverStation::Alliance::kRed) {
		Robot::arduinoComm->WriteTest("R"); // Will use red color.
	}
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Ascend::Interrupted() {
	Ascend::End();
}
